Vagrant.configure("2") do |config|
  # הגדרת האימג' - CentOS 7 נחשב לקל ויציב מאוד למעבדות
  config.vm.box = "centos/7"

  # לולאה ליצירת 4 שרתים: srv1, srv2, srv3, srv4
  (1..4).each do |i|
    config.vm.define "srv#{i}" do |node|
      
      # הגדרת כתובת IP פרטית לכל שרת (לצורך תקשורת ביניהם)
      node.vm.network "private_network", ip: "192.168.56.1#{i}"
      
      # הגדרת שם המארח (Hostname) בתוך הלינוקס
      node.vm.hostname = "srv#{i}"

      # הגדרות משאבים ב-VirtualBox
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "512"  # חצי ג'יגה ראם לכל שרת
        vb.cpus = 1        # ליבה אחת לכל שרת
        vb.name = "CentOS-Srv#{i}" # השם שיופיע בממשק של VirtualBox
      end
    end
  end
end