Vagrant.configure("2") do |config|
  # הגדרת ה-Box המשותף לכולן
  config.vm.box = "generic/centos9s"
  
  # יצירת 3 מכונות בלולאה
  (1..5).each do |i|
    config.vm.define "srv#{i}" do |node|
      
      # הגדרת שם המכונה וכתובת ה-IP (192.168.56.11, .12, .13)
      node.vm.network "private_network", ip: "192.168.56.#{10 + i}"
      
      # הגדרת משאבי מערכת לכל מכונה
      node.vm.provider "virtualbox" do |vb|
        vb.name = "srv#{i}"
        vb.memory = "1024"
        vb.cpus = 1
      end

      # Provisioning: עדכון המערכת רק בהרצה הראשונה
      node.vm.provision "shell", inline: <<-SHELL
        echo "Updating srv#{i} system..."
        sudo dnf update -y
      SHELL
    end
  end
end