name: Vagrant Lab CI-CD

on:
  push:
    branches:
      - master  # ה-Pipeline יופעל רק כשמתבצע Push לענף master
    paths:
      - 'Vagrantfile' # ה-Pipeline ירוץ רק כשיש שינוי בקובץ הזה

jobs:
  vagrant-deploy:
    # שימוש ב-Labels המדויקים מה-Runner שלך (image_ef9702.png)
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # מושך את הקבצים למחשב

      - name: Deploy Vagrant Lab
        run: |
          # הרצת הפקודה באמצעות ה-Runner שרץ תחת המשתמש gabi
          vagrant up --provision