name: Vagrant Lab CI-CD

on:
  push:
    branches:
      - master
    paths:
      - 'Vagrantfile'
  workflow_dispatch: # שומר על האפשרות להפעיל ידנית מהאתר

jobs:
  vagrant-deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Vagrant Lab
        # המשתנה הזה מבטיח שה-Runner ירוץ בדיוק בתיקייה שבה נמצא ה-Vagrantfile
        working-directory: ${{ github.workspace }}
        run: |
          echo "Verifying location:"
          dir
          vagrant up --provision