name: Vagrant Lab CI-CD

on:
  push:
    branches:
      - master
    paths:
      - 'vagrant-dev-lab/Vagrantfile' # עדכון הנתיב גם כאן ליתר ביטחון
  workflow_dispatch:

jobs:
  vagrant-deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Vagrant Lab
        # כאן אנחנו נכנסים לתיקייה שראינו ב-dir
        working-directory: ${{ github.workspace }}/vagrant-dev-lab
        run: |
          echo "Current location content:"
          dir
          vagrant up --provision